### ISSUE TITLE
Basic look and feel

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/tech_for_good_hub_data#2]
See http://techforgoodhub.com/

**Comment by drkane** [comment]
Nicely organised stylesheet: <http://techforgoodhub.com/wp-content/themes/businessx/style.css?ver=1.0.5.5>

**Comment by suninthesky** [comment]
Nice. https://github.com/slime-lang/slime might be worth a look for keeping the markup minimal.

**Comment by drkane** [comment]
Wireframe for possible display of multiple projects on a page: https://drive.google.com/open?id=0B989L2QQ0BWKWWNHYkZENU9PVU0

**Comment by suninthesky** [comment]
Looks great.

**Comment by drkane** [comment]
Commits 9e4d7f3765a36b3e3e3a0775d6115a067bba89ef, cfa5da10f9447bc13b10d5b5c159948bbb82943f, 10f273b98fc0b13d60e258151b1c41c580c11c40
