### ISSUE TITLE
Ensure valid urls

### ISSUE THREAD

**Issue by suninthesky** [TechforgoodCAST/tech_for_good_hub_data#51]
E.g.

- `/proposals/www.communityconnect.today`
- `http://localhost:4000/proposals/www.abccounsellingservices.com`
- `http://localhost:4000/proposals/n/a`
- `https://pacific-anchorage-87091.herokuapp.com/%20%20%20%20%20%20%20%20%20Please%20note%20that%20this%20is%20the%20demo%20version%20of%20our%20web-app,%20so%20as%20not%20to%20influence%20our%20testing%20data.`

**Comment by drkane** [comment]
Data cleaned to remove malformed urls

**Comment by suninthesky** [comment]
Suggest also https://hexdocs.pm/ecto/Ecto.Changeset.html#validate_format/4
